### ISSUE TITLE
Apply TDD on dataset preprocessing

### ISSUE THREAD

**Issue by georgiana-ojoc** [georgiana-ojoc/LandmarkRetrieval#23]
1. First iteration
- Failed tests
![1 fail](https://user-images.githubusercontent.com/46318081/140011527-92a14b30-6dd7-44e2-baec-5bbd0a510d4b.png)
- Passed tests
![1 success](https://user-images.githubusercontent.com/46318081/140011539-45b8a0c7-caca-4e90-9f62-207e7ea7553c.png)
2. Second iteration
- Failed tests
![2 fail](https://user-images.githubusercontent.com/46318081/140011574-d9cdb62d-316f-48ae-aff0-916ae8778305.png)
- Passed tests
- ![2 success](https://user-images.githubusercontent.com/46318081/140011623-aab90ddd-858b-4c2d-8b2a-1d7d87e2ace4.png)

**Comment by gabriela0neagu** [comment]
1. First iteration

- Failed tests
![GN_it1_poza1](https://user-images.githubusercontent.com/56290987/140019313-1bdb26a5-603f-43b1-9053-5e4c0d2e1ab8.PNG)

- Passed tests
![GN_it1_poza2](https://user-images.githubusercontent.com/56290987/140019343-db3f944b-e990-40b7-8455-5907bf951421.PNG)

2. Second iteration

- Failed tests
![GN_it2_poza1](https://user-images.githubusercontent.com/56290987/140019356-b36c7778-7229-469e-95c8-fab3f1c03563.PNG)

- Passed tests
![GN_it2_poza2](https://user-images.githubusercontent.com/56290987/140019374-3283ed3c-0177-431e-a27a-974fedfd0675.PNG)
